### ISSUE TITLE
Ajouter le Nantes MongoDB User Group à la liste

### ISSUE THREAD

**Issue by padewitte** [devconferences/devconferences-2#22]
Que devons nous fournir pour que le Nantes MongoDB User Group soit ajouté à la liste des user group nantais ?

**Comment by sebprunier** [comment]
Je ne sais pas pourquoi il a disparu, je regarde ca !

**Comment by sebprunier** [comment]
Fixed By @cwoodrow

**Comment by cwoodrow** [comment]
Look and be amazed :D : http://www.devconferences.org/city/Nantes
A+
C.

2015-08-28 10:01 GMT+02:00 Sébastien Prunier notifications@github.com:

**Comment by padewitte** [comment]
Thanks
